name: CI Workflow

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest # Specify the runner environment

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1 # Action to check out the repository code
    - name: Run a one-line script
      run: echo Hello, world! # Execute a shell command
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
    - name: Vc check with renovate
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        
    - name: download
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
